baseURL: "https://jam.tips/"
languageCode: "en-us"
title: "JAMtips"
pygmentsstyle: 'monokai'
paginate: 6
social:
  twitter: "https://twitter.com/rmonteroo"
  github: "https://github.com/rob-p2/jam.tips"
  instagram: "https://instagram.com/rmonteroo"
  linkedin: "https://www.linkedin.com/in/rmontero/"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors
